#!/bin/bash
# Auto-setup: Fetch secrets and deploy Klarpakke
# Usage: bash scripts/auto-setup-env.sh

set -euo pipefail

echo "🤖 Klarpakke Auto-Setup"
echo "======================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Project config
PROJECT_REF="swfyuwkptusceiouqlks"
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"

# Check if .env exists with real values
if [ -f ".env" ] && grep -q "eyJ" .env 2>/dev/null; then
    echo -e "${GREEN}✅ .env already exists with secrets${NC}"
    source .env
    SKIP_ENV=true
else
    SKIP_ENV=false
fi

if [ "$SKIP_ENV" = false ]; then
    echo "📥 Fetching Supabase secrets..."
    echo ""
    echo "Option 1: Paste your Supabase keys manually"
    echo "Option 2: Login to Supabase CLI (auto-fetch)"
    echo ""
    read -p "Choose method (1 or 2): " -n 1 -r METHOD
    echo ""
    echo ""

    if [ "$METHOD" = "2" ]; then
        # Try to fetch from Supabase CLI
        echo "🔐 Attempting to fetch secrets from Supabase..."
        
        if ! command -v supabase &> /dev/null; then
            echo -e "${RED}❌ Supabase CLI not found${NC}"
            echo "Install: brew install supabase/tap/supabase"
            exit 1
        fi
        
        # Login if needed
        if ! supabase projects list &>/dev/null; then
            echo "Please login to Supabase:"
            supabase login
        fi
        
        # Get project API keys
        echo "Fetching API keys for project $PROJECT_REF..."
        
        # Link project first
        supabase link --project-ref "$PROJECT_REF" || {
            echo -e "${RED}❌ Failed to link project${NC}"
            exit 1
        }
        
        # Try to get keys from project settings
        echo -e "${YELLOW}⚠️  Auto-fetch from CLI not fully supported yet${NC}"
        echo "Falling back to manual input..."
        METHOD="1"
    fi
    
    if [ "$METHOD" = "1" ]; then
        echo "🔑 Manual Secret Entry"
        echo ""
        echo "Get your keys from:"
        echo "  https://supabase.com/dashboard/project/$PROJECT_REF/settings/api"
        echo ""
        
        echo "Paste SUPABASE_ANON_KEY (starts with 'eyJ'):"
        read -r ANON_KEY
        
        echo "Paste SUPABASE_SECRET_KEY (service_role, starts with 'eyJ'):"
        read -r SECRET_KEY
        
        echo ""
        echo "Optional: Paste PPLX_API_KEY (or press Enter to skip):"
        read -r PPLX_KEY
        
        # Create .env
        cat > .env << EOF
# Auto-generated by scripts/auto-setup-env.sh
# $(date)

SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SECRET_KEY=$SECRET_KEY
SUPABASE_PROJECT_REF=$PROJECT_REF
EOF

        if [ -n "$PPLX_KEY" ]; then
            echo "PPLX_API_KEY=$PPLX_KEY" >> .env
        fi
        
        echo -e "${GREEN}✅ .env file created${NC}"
        echo ""
    fi
    
    # Load env
    source .env
fi

# Verify env vars
echo "🔍 Verifying environment variables..."
if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
    echo -e "${RED}❌ Missing required env vars${NC}"
    echo "Please ensure .env has:"
    echo "  - SUPABASE_URL"
    echo "  - SUPABASE_ANON_KEY"
    echo "  - SUPABASE_SECRET_KEY"
    exit 1
fi

echo -e "${GREEN}✅ Environment variables loaded${NC}"
echo "  SUPABASE_URL: $SUPABASE_URL"
echo "  SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:0:20}..."
echo ""

# Test Supabase connection
echo "🔌 Testing Supabase connection..."
RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "apikey: $SUPABASE_ANON_KEY" \
    -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
    "$SUPABASE_URL/rest/v1/" 2>/dev/null || echo "error\n000")

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)

if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "404" ]; then
    echo -e "${GREEN}✅ Supabase connection OK${NC}"
else
    echo -e "${RED}❌ Supabase connection failed: HTTP $HTTP_CODE${NC}"
    echo "Please verify your SUPABASE_ANON_KEY"
    exit 1
fi
echo ""

# Link Supabase project
echo "🔗 Linking Supabase project..."
if supabase link --project-ref "$PROJECT_REF" 2>&1 | grep -q "Finished"; then
    echo -e "${GREEN}✅ Project linked${NC}"
else
    echo -e "${YELLOW}⚠️  Link may have failed, but continuing...${NC}"
fi
echo ""

# Deploy migrations
echo "📤 Deploying Supabase migrations..."
echo ""

if [ -d "supabase/migrations" ] && [ -n "$(ls -A supabase/migrations/*.sql 2>/dev/null)" ]; then
    echo "Migrations found:"
    ls -1 supabase/migrations/*.sql
    echo ""
    
    read -p "Deploy migrations now? (Y/n): " -n 1 -r DEPLOY
    echo ""
    
    if [[ $DEPLOY =~ ^[Yy]$ ]] || [ -z "$DEPLOY" ]; then
        # Try Supabase CLI first
        if supabase db push 2>&1; then
            echo -e "${GREEN}✅ Migrations deployed via Supabase CLI${NC}"
        else
            echo -e "${YELLOW}⚠️  CLI deploy failed, trying direct SQL execution...${NC}"
            
            # Fallback: Execute SQL directly via REST API
            for migration in supabase/migrations/*.sql; do
                echo "Executing: $(basename "$migration")"
                
                # Read SQL file
                SQL_CONTENT=$(cat "$migration")
                
                # Execute via Supabase SQL editor endpoint (if available)
                # Note: This requires service_role key
                if [ -n "${SUPABASE_SECRET_KEY:-}" ]; then
                    # This is a simplified approach - production would use proper SQL execution
                    echo "  ⚠️  Manual SQL execution required"
                    echo "  Copy-paste this into Supabase SQL Editor:"
                    echo "  https://supabase.com/dashboard/project/$PROJECT_REF/editor"
                fi
            done
        fi
    fi
else
    echo -e "${YELLOW}⚠️  No migrations found in supabase/migrations/${NC}"
fi
echo ""

# Run smoke test
echo "🧪 Running smoke tests..."
if [ -f "scripts/smoke-test.sh" ]; then
    if bash scripts/smoke-test.sh; then
        echo -e "${GREEN}✅ Smoke tests passed${NC}"
    else
        echo -e "${YELLOW}⚠️  Some tests failed (this is OK for first setup)${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  Smoke test script not found${NC}"
fi
echo ""

# Summary
echo "="======================"
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "="======================"
echo ""
echo "Next steps:"
echo "  1. Verify migrations in Supabase:"
echo "     https://supabase.com/dashboard/project/$PROJECT_REF/editor"
echo ""
echo "  2. Test manually:"
echo "     source .env"
echo "     bash scripts/smoke-test.sh"
echo ""
echo "  3. Export KPIs (when you have data):"
echo "     bash scripts/export-kpis.sh 30"
echo ""
echo "  4. Setup Make.com scenarios:"
echo "     - Import: make/scenarios/*.json"
echo "     - Add env vars in Make UI"
echo ""
