#!/bin/bash
echo "🔐 Make API Token Generator Guide"
echo ""
echo "1. Go to: https://eu1.make.com/organization/733572/api-tokens"
echo "2. Click: 'Add Token'"
echo "3. Add these scopes:"
echo "   ✅ scenarios:read"
echo "   ✅ scenarios:write"
echo "   ✅ scenarios:execute"
echo "   ✅ connections:read"
echo "   ✅ connections:write"
echo "4. Copy new token"
echo "5. Update .env.migration:"
echo "   MAKE_API_TOKEN='new-token-here'"
