#!/bin/bash
# Hjelpeverktøy: Instruksjoner for å hente Supabase keys

echo "🔑 Slik henter du EKTE Supabase keys:"
echo "========================================"
echo ""
echo "1. Åpne Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/swfyuwkptusceiouqlks"
echo ""
echo "2. Gå til: Settings → API (i venstre sidebar)"
echo ""
echo "3. Kopier disse verdiene:"
echo ""
echo "   a) Project URL:"
echo "      Ser ut som: https://swfyuwkptusceiouqlks.supabase.co"
echo "      → Sett som SUPABASE_URL"
echo ""
echo "   b) anon / public key:"
echo "      Starter med: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "      → Sett som SUPABASE_ANON_KEY"
echo ""
echo "   c) service_role / secret key:"
echo "      Starter med: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "      → Sett som SUPABASE_SECRET_KEY"
echo ""
echo "4. Gå til: Settings → API → Access Tokens (scroll ned)"
echo ""
echo "   d) Klikk 'Generate New Token'"
echo "      - Name: 'Klarpakke Deploy'"
echo "      - Expiration: 1 year"
echo "      Starter med: sbp_..."
echo "      → Sett som SUPABASE_ACCESS_TOKEN"
echo ""
echo "5. Kopier PROJECT REF (fra URL):"
echo "      swfyuwkptusceiouqlks"
echo "      → Sett som SUPABASE_PROJECT_REF"
echo ""
echo "6. Lim inn i .env fil:"
echo "   nano .env"
echo ""
echo "7. Test at verdiene er gyldige:"
echo "   bash scripts/validate-env.sh"
echo ""
