#!/bin/bash

echo "🔑 Getting Supabase API Keys..."
echo ""
echo "📍 Go to: https://supabase.com/dashboard/project/swfyuwkptusceiouqlks/settings/api"
echo ""
echo "You need TWO keys:"
echo ""
echo "1️⃣  anon / public key"
echo "   - Starts with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   - Label: 'anon public'"
echo "   - Safe to use in browser"
echo ""
echo "2️⃣  service_role key (OPTIONAL, for bypassing RLS)"
echo "   - Starts with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   - Label: 'service_role secret'"
echo "   - Keep this SECRET!"
echo ""
echo "════════════════════════════════════════"
echo "After copying keys, update .env:"
echo ""
echo "# Remove old invalid key"
echo "sed -i.bak '/SUPABASE_ANON_KEY=/d' .env"
echo ""
echo "# Add new keys"
echo 'echo "SUPABASE_ANON_KEY=paste_anon_key_here" >> .env'
echo 'echo "SUPABASE_SERVICE_KEY=paste_service_role_key_here" >> .env'
echo ""
echo "Then test: npm run webflow:sync"
echo "════════════════════════════════════════"
