#!/usr/bin/env bash
set -euo pipefail

# Quick Manual Setup - bypasser Supabase CLI issues

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "🚀 Klarpakke Quick Setup"
echo "========================="
echo ""
echo "Dette scriptet hjelper deg å sette opp .env manuelt."
echo ""

# Check if .env exists
if [[ -f .env ]]; then
  echo "📁 Fant eksisterende .env-fil"
  echo ""
  
  # Load existing values
  set +e
  EXISTING_ACCESS_TOKEN=$(grep SUPABASE_ACCESS_TOKEN .env 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | xargs)
  EXISTING_PROJECT_REF=$(grep SUPABASE_PROJECT_REF .env 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | xargs)
  EXISTING_URL=$(grep SUPABASE_URL .env 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | xargs)
  EXISTING_ANON_KEY=$(grep SUPABASE_ANON_KEY .env 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | xargs)
  EXISTING_SERVICE_KEY=$(grep SUPABASE_SERVICE_ROLE_KEY .env 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | xargs)
  set -e
  
  echo "Nåværende verdier:"
  [[ -n "$EXISTING_ACCESS_TOKEN" ]] && echo "  ✓ ACCESS_TOKEN: ${EXISTING_ACCESS_TOKEN:0:10}..."
  [[ -n "$EXISTING_PROJECT_REF" ]] && echo "  ✓ PROJECT_REF: $EXISTING_PROJECT_REF"
  [[ -n "$EXISTING_URL" ]] && echo "  ✓ URL: $EXISTING_URL"
  [[ -n "$EXISTING_ANON_KEY" ]] && echo "  ✓ ANON_KEY: ${EXISTING_ANON_KEY:0:20}..."
  [[ -n "$EXISTING_SERVICE_KEY" ]] && echo "  ✓ SERVICE_ROLE_KEY: ${EXISTING_SERVICE_KEY:0:20}..."
  echo ""
  
  read -p "Vil du oppdatere verdier? (y/n): " UPDATE
  if [[ "$UPDATE" != "y" ]]; then
    echo "Avbryter..."
    exit 0
  fi
  
  # Backup
  cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
  echo "✓ Backup opprettet"
  echo ""
fi

echo "📝 Samler inn Supabase-opplysninger"
echo "====================================="
echo ""
echo "Du finner disse verdiene i Supabase Dashboard:"
echo "https://supabase.com/dashboard"
echo ""

# Access Token
echo "1️⃣  Access Token (sbp_...)"
echo "   Hvor: https://supabase.com/dashboard/account/tokens"
echo "   Klikk 'Generate new token' om du ikke har det"
echo ""
read -p "   Paste Access Token: " ACCESS_TOKEN

if [[ ! "$ACCESS_TOKEN" =~ ^sbp_ ]]; then
  echo ""
  echo "❌ Ugyldig format! Token må starte med 'sbp_'"
  exit 1
fi

echo "   ✓ Token godkjent: ${ACCESS_TOKEN:0:10}..."
echo ""

# Project Ref
echo "2️⃣  Project Reference ID (20 små bokstaver)"
echo "   Hvor: Supabase Dashboard → Velg prosjekt"
echo "   URL: https://supabase.com/dashboard/project/[PROJECT_REF]"
echo "   Eller: Settings → General → Reference ID"
echo ""
read -p "   Paste Project Ref (20 tegn): " PROJECT_REF

if [[ ! "$PROJECT_REF" =~ ^[a-z]{20}$ ]]; then
  echo ""
  echo "❌ Ugyldig format! Må være eksakt 20 små bokstaver."
  echo "   Eksempel: abcdefghijklmnopqrst"
  exit 1
fi

echo "   ✓ Project Ref: $PROJECT_REF"
echo ""

# Generate URL
PROJECT_URL="https://${PROJECT_REF}.supabase.co"
echo "3️⃣  Project URL (generert automatisk)"
echo "   ✓ $PROJECT_URL"
echo ""

# Anon Key
echo "4️⃣  Anon Key (eyJ...)"
echo "   Hvor: Dashboard → Settings → API → anon key"
echo ""
read -p "   Paste Anon Key: " ANON_KEY

if [[ ! "$ANON_KEY" =~ ^eyJ ]]; then
  echo ""
  echo "❌ Ugyldig format! Anon Key starter normalt med 'eyJ'"
  read -p "   Er du sikker? (y/n): " CONFIRM
  if [[ "$CONFIRM" != "y" ]]; then
    exit 1
  fi
fi

echo "   ✓ Anon Key: ${ANON_KEY:0:20}..."
echo ""

# Service Role Key
echo "5️⃣  Service Role Key (eyJ...)"
echo "   Hvor: Dashboard → Settings → API → service_role key (secret)"
echo "   ⚠️  VIKTIG: Dette er SERVICE_ROLE, ikke anon!"
echo ""
read -p "   Paste Service Role Key: " SERVICE_KEY

if [[ ! "$SERVICE_KEY" =~ ^eyJ ]]; then
  echo ""
  echo "❌ Ugyldig format! Service Role Key starter normalt med 'eyJ'"
  read -p "   Er du sikker? (y/n): " CONFIRM
  if [[ "$CONFIRM" != "y" ]]; then
    exit 1
  fi
fi

echo "   ✓ Service Role Key: ${SERVICE_KEY:0:20}..."
echo ""

# Write .env
echo "💾 Lagrer til .env..."
echo "====================="
echo ""

cat > .env << EOF
# Supabase Configuration
# Generated by quick-setup.sh on $(date)

# Project Settings
SUPABASE_PROJECT_REF=$PROJECT_REF
SUPABASE_URL=$PROJECT_URL

# API Keys
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

# CLI Access Token (for deployment)
SUPABASE_ACCESS_TOKEN=$ACCESS_TOKEN

# Optional: Add other keys below
# PPLX_API_KEY=
# WEBFLOW_API_TOKEN=
EOF

echo "✓ .env opprettet!"
echo ""

# Verify
echo "✅ Verifiserer oppsett..."
echo "=========================="
echo ""

# Load .env
set -a
source .env
set +a

echo "1. Project Ref lengde:"
if [[ ${#SUPABASE_PROJECT_REF} -eq 20 ]]; then
  echo "   ✓ $SUPABASE_PROJECT_REF (lengde: 20)"
else
  echo "   ❌ Feil lengde: ${#SUPABASE_PROJECT_REF} (skal være 20)"
fi

echo ""
echo "2. Access Token format:"
if [[ "$SUPABASE_ACCESS_TOKEN" =~ ^sbp_ ]]; then
  echo "   ✓ Starter med 'sbp_'"
else
  echo "   ❌ Feil format (skal starte med 'sbp_')"
fi

echo ""
echo "3. API connectivity:"
if curl -fsS -H "apikey: $SUPABASE_ANON_KEY" "$SUPABASE_URL/rest/v1/" >/dev/null 2>&1; then
  echo "   ✓ API-tilkobling fungerer!"
else
  echo "   ⚠️  Kunne ikke koble til API (kan være RLS-policy, men nøklene er sannsynligvis riktige)"
fi

echo ""
echo "============================="
echo "✅ Setup fullført!"
echo "============================="
echo ""
echo "📋 Neste steg:"
echo ""
echo "1. Test lokal deploy:"
echo "   npm run ci:all"
echo ""
echo "2. Sync til GitHub Secrets:"
echo "   bash scripts/sync-github-secrets.sh"
echo ""
echo "3. Trigger CI/CD pipeline:"
echo "   gh workflow run '🚀 Auto-Deploy Pipeline' --ref main -f environment=staging"
echo ""
echo "📁 .env-fil lagret i: $ROOT_DIR/.env"
echo ""
